"""add language to posts

Revision ID: 64090bc41737
Revises: 0c42ce863ae0
Create Date: 2021-01-31 22:02:20.728051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64090bc41737'
down_revision = '0c42ce863ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
